apiVersion: apps/v1
kind: Deployment
metadata:
  name: pythondeployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mypythonapp
  template:
    metadata:
      labels:
        app: mypythonapp
    spec:
      containers:
      - name: pythonapppipeline
        image: myacr2211.azurecr.io/oferae/pythonapppipeline:#{Build.BuildId}#
        ports:
        - containerPort: 5000
# service type loadbalancer       
---
apiVersion: v1
kind: Service
metadata:
  name: mypythonappsvc
spec:
  selector:
    app: mypythonapp
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  type: LoadBalancer
